<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('nodes', function (Blueprint $table) {
            // The business identity of a request: FIN-2026-0107, quoted in
            // conversation and printed in every notification. Nullable because
            // only nodes created by a form submission carry one — a task
            // written by hand has no process to be numbered under. Nothing like
            // the opaque code that addresses a node in a URL; the two never
            // substitute for each other (12-platform-foundation.md).
            $table->string('reference')->nullable()->after('title');

            // Who brought the node into existence. What "the requester's
            // manager" resolves from, and what lets a submitter follow their
            // own request on a board they otherwise cannot browse. Null for a
            // node generated by a flow, where nobody personally did.
            $table->foreignId('creator_id')->nullable()->after('assignee_id')->constrained('users')->nullOnDelete();

            // Assigned once, never changed, never reused — within the tenant,
            // which is the only place it is ever quoted.
            $table->unique(['organization_id', 'reference']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('nodes', function (Blueprint $table) {
            $table->dropUnique(['organization_id', 'reference']);
            $table->dropConstrainedForeignId('creator_id');
            $table->dropColumn('reference');
        });
    }
};
